### ISSUE TITLE
ReferenceError: _ is not defined 

### ISSUE THREAD

**Issue by davidfilip** [0xfe/fretboard#1]
I am creating new Fretboard using this simple code: 

var d = $("#fDiv");
var f = new Vex.Flow.FretboardDiv(d).build();

There is also some div that contains some example code (or is empty). 

After I tried to run the code there is error in my developer console: 
Uncaught ReferenceError: _ is not defined    fretboard.js:40

The code on this line is: _.extend(this.options, options);

After I comment this line (and another line like this) everything seems to be working, but I still feel like there is something not working right. 

Is this problem of Fretboard or did I miss something?

**Comment by 0xfe** [comment]
You need to include either `underscore.js` or `lodash.js` (Both open source libraries -- either one will work.)

If you keep the line commented, the custom options will not take effect.
